### ISSUE TITLE
Releases v1.5.0 (and previous) not compatible with Expo 38

### ISSUE THREAD

**Issue by benediktdertinger** [LinusU/react-native-get-random-values#17] opened 2020-09-10 09:16 UTC
Using **v1.5.0** with Expo SDK 38 fails with `Expo managed workflow support for react-native-get-random-values is only available in SDK 39 and higher.`

Switching to **v1.4.0 (or lower)** leads to `TypeError: null is not an object (evaluating 'RNGetRandomValues.getRandomBase64'`.

Any recommendations on how to use this lib with Expo SDK 38?

**Comment by ctavan** [comment] 2020-09-10 09:23
Unfortunately you will have to wait until Expo SDK 39 comes out, see https://github.com/LinusU/react-native-get-random-values/issues/16#issuecomment-690025702 (should happen in the next couple of days).

**Comment by LinusU** [comment] 2020-09-10 13:33
duplicate of #16 😅

**Closed by LinusU** 2020-09-10 13:33 UTC
